name: Java_CI
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: Clone-down
      uses: actions/checkout@v2 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: .
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: .
    - name: Test
      run: bash ci/unit-test-app.sh
  third_job:
    needs: first_job
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: .
    - name: Build
      run: bash ci/build-app.sh
    - name: Upload a Build Artifact 2
      uses: actions/upload-artifact@v2
      with:
        name: build2-artifact
        path: .
  docker_image:
    needs: [second_job,third_job]
    runs-on: ubuntu-latest
    env:
      docker_username: ${{ secrets.DOCKER_USER }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Download a single artifact 2
      uses: actions/download-artifact@v2
      with:
        name: build2-artifact
        path: .
    - name: Docker Build
      run: ci/build-docker.sh
      with: export GIT_COMMIT="GA-$GITHUB_SHA"
    - name: Docker Push
      run: ci/push-docker.sh
      with: export GIT_COMMIT="GA-$GITHUB_SHA"
