name: pipe-with-unit-test
on: push
jobs:
  my-job:
    name: job-name
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2 
      -  run: ci/build-app.sh
      - name: Unit-test
        run: ci/unit-test-app.sh